# Generated by Django 5.0.3 on 2024-04-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
